// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CheatInput: typeof import('./components/CheatInput.vue')['default']
    LazyImg: typeof import('./components/common/LazyImg.vue')['default']
    LoginModal: typeof import('./components/LoginModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheBed: typeof import('./components/TheBed.vue')['default']
    TheBox: typeof import('./components/common/TheBox.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheHeader: typeof import('./components/TheHeader.vue')['default']
    TheUser: typeof import('./components/TheUser.vue')['default']
  }
}
